name: Build and Release

on:
  push:
    branches: [ "**" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package --no-transfer-progress

      - name: Rename jar
        run: mv target/AntiCreeper-1.0.jar target/AntiCreeper.jar

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: release
          name: AntiCreeper
          files: target/AntiCreeper.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}